:PACKAGE: graphviz 

.SOURCE.h : ../../lib/cdt ../../lib/graph ../../lib/gvc ../../lib/common \
        ../../lib/pathplan

gvplugin_dot_layout $(LIBVERSION) :LIBRARY: gvlayout_dot_layout.c \
	gvplugin_dot_layout.c \
	-lcommon

