:PACKAGE: graphviz

.SOURCE.h : ../cdt ../graph ../common ../neatogen ../gvc ../pack ../pathplan

fdpgen $(LIBVERSION) :LIBRARY: clusteredges.c comp.c dbg.c fdpinit.c grid.c \
	layout.c tlayout.c xlayout.c \
	-lneatogen


