:PACKAGE: graphviz

.SOURCE.h : ../cdt ../graph ../common ../neatogen ../gvc ../pack ../pathplan

circogen $(LIBVERSION) :LIBRARY: block.c blockpath.c blocktree.c circpos.c \
	circular.c circularinit.c deglist.c edgelist.c nodelist.c nodeset.c \
	stack.c \
	-lneatogen


