:PACKAGE: graphviz 

.SOURCE.h : ../../lib/cdt ../../lib/graph ../../lib/gvc ../../lib/common \
        ../../lib/pathplan

gvplugin_pango $(LIBVERSION) :LIBRARY: gvloadimage_pango.c gvplugin_pango.c \
	gvrender_pango.c gvtextlayout_pango.c

