:PACKAGE: graphviz

.SOURCE.h : ../cdt ../graph ../common ../gvc ../pack ../pathplan

neatogen $(LIBVERSION) :LIBRARY: adjust.c bfs.c circuit.c closest.c \
	compute_hierarchy.c conjgrad.c constrained_majorization.c \
	constrained_majorization_ipsep.c constraint.c dijkstra.c edges.c \
	embed_graph.c find_ints.c geometry.c heap.c hedges.c info.c intersect.c \
	kkutils.c legal.c lu.c matinv.c matrix_ops.c memory.c mosek_quad_solve.c \
	neatoinit.c neatosplines.c opt_arrangement.c pca.c poly.c printvis.c \
	quad_prog_solve.c quad_prog_vpsc.c site.c smart_ini_x.c solve.c \
	stress.c stuff.c voronoi.c \
	-lgvc -lpack


