:PACKAGE: graphviz 

.SOURCE.h : ../../lib/cdt ../../lib/graph ../../lib/gvc ../../lib/common \
        ../../lib/pathplan

gvplugin_neato_layout $(LIBVERSION) :LIBRARY: gvlayout_neato_layout.c \
	gvplugin_neato_layout.c \
	-lcommon

