:PACKAGE: graphviz

.SOURCE.h : ../cdt ../graph ../common ../gvc ../pack ../pathplan

dotgen $(LIBVERSION) :LIBRARY: acyclic.c class1.c class2.c cluster.c \
	compound.c conc.c decomp.c dotinit.c dotsplines.c fastgr.c flat.c \
	mincross.c position.c rank.c sameport.c \
	-lcommon


