:PACKAGE: graphviz

gd $(LIBVERSION) :LIBRARY: gd.c gd_gd.c gd_gd2.c gd_io.c gd_io_dp.c \
	gd_io_file.c gd_ss.c gd_io_ss.c gd_gif_in.c gd_gif_out.c gd_jpeg.c \
	gd_png.c gdcache.c gdfontg.c gdfontl.c gdfontmb.c gdfonts.c gdfontt.c \
	gdhelpers.c gdkanji.c gdtables.c gdft.c gdxpm.c \
	wbmp.c gd_wbmp.c gd_topal.c gdfx.c gd_security.c \
	-lpng -lft -ljpeg -lz


