:PACKAGE: graphviz

cdt $(LIBVERSION) :LIBRARY: cdt.3 \
	dtclose.c dtdisc.c dtextract.c dtflatten.c dthash.c \
	dtlist.c dtmethod.c dtopen.c dtrenew.c dtrestore.c \
	dtsize.c dtstat.c dtstrhash.c dttree.c dtview.c dtwalk.c

$(INCLUDEDIR) :INSTALLDIR: cdt.h

:: cdt.pdf
